### PR TITLE
Bump Balrog UI deps

### PR DESCRIPTION
**Pull request by gabrielBusta**
Bumps Balrog dependencies and node version.

### CODE REVIEW

**Comment by gbrownmozilla** [comment]
@gabrielBusta With such a big change to yarn.lock, I'm surprised you aren't updating package.json (other than node). Just checking, that's intentional?

**Comment by gabrielBusta** [comment]
Yeah it is. The `^` in the `package.json` means update to the latest `patch` or `minor` version on `yarn install`. Here we are updating the packages to the latest `patch` version at most. I might change the `package.json` to do some major version updates (I would like to migrate our UIs to Material UI v5 and React 18). But those updates require more careful consideration to deal with breaking changes.

**Review by gbrownmozilla — CHANGES_REQUESTED** [review]
Thanks for this.
Your changes look OK to me, but when I run them locally (on Ubuntu), I cannot load the Admin interface: https://localhost:9000 is not being served. Curiously, I don't see any failures on the console.

**Comment by gabrielBusta** [comment]
Deleting `ui/node_modules` and running `yarn install` might help. Odd that it doesn't show failures on the console.

**Comment by gbrownmozilla** [comment]
Aha! I cleared my browser site data for localhost...was prompted with the security warning...accepted and all's well!

**Review by gbrownmozilla — APPROVED** [review]

**Pull request merged**
