### PR TITLE
WIP - RELENG-941: Display used Releases, unless unused requested

### PR DESCRIPTION
**Pull request by gabrielbusta**
Issue #2561 - Consider only displaying "used" Releases, unless unused requested

### CODE REVIEW

**Comment by escapewindow** [comment]
As mentioned in the jira ticket, we often add a new release and need to be able to view it/reference it in a rule change. So rather than hiding all unused, I’d prefer if we hid unused-and-older-than-time-threshold.

**Comment by gabrielBusta** [comment]
This is a toggle switch that hides/un-hides the unreferenced releases. If we need to look at the unreferenced releases we can toggle it. Right now it defaults to hiding the unreferenced releases. But maybe it'd make more sense to show all releases by default and have that switch there to quickly filter the unreferenced releases.

**Comment by escapewindow** [comment]
Is it difficult to have the toggle hide/show unused-but-older-than, say, 6 months releases?

**Comment by gabrielBusta** [comment]
Yeah that’s totally doable. The toggle could hide/show unused releases older than 6 months.

**Comment by gbrownmozilla** [comment]
+1 for hiding unused-and-older-than-X; the newly added release is an important consideration. I would think X=a few days would be fine, but 6 months is okay with me too.

**Comment by gabrielBusta** [comment]
I may have spoken too soon. It doesn't look like the Balrog releases keep track of the date they are created. The ShipIt releases are the ones with a "created" timestamp.

**Pull request closed without merging**
