### PR TITLE
Fix pyjwt dependency issues

### PR DESCRIPTION
**Pull request by gabrielBusta**
Pining pyjwt to 2.4.0 fixed the issue.
When I run `pip-compile-multi` for some reason it updates `repoze.lru` to `repoze-lru` in the generated `.txt` requirements... I fixed it manually by replacing `-` with `.` and now it works

### CODE REVIEW

**Review by gbrownmozilla — APPROVED** [review]
I think this is fine and gets us unstuck. 

We should follow-up on the larger pip-compile-multi / repoze.lru issue, perhaps with a pin.sh like in scriptworker-scripts.

**Comment by jcristau** [comment]
Do we understand why the pyjwt dep started breaking?

**Comment by gabrielBusta** [comment]
A dependency clash? Hard to tell. What if we switched to poetry?

**Comment by gabrielBusta** [comment]
Maybe we can standardize on a `pip-compile-multi` version?

I could follow through with the deprecation of repoze.lru

It will take a while because the tests broke all over the place and cachetools doesn't keep stats (used in the tests)

**Pull request merged**
