### PR TITLE
UI shows scheduled deletions for unrelated channels2

### PR DESCRIPTION
**Pull request by AMUZY**
Hi @bhearsum . So I figured out the error in the `ruleMatchesChannel` function. All that was needed to fix the issue was a refactoring of the conditional statements in it and updating the test suites for it. Works now.

From : 
```
const scChannelMatches = rule.scheduledChange
    ? rule.scheduledChange.channel === null ||
        rule.scheduledChange.channel === '' ||
        rule.scheduledChange.channel === channel ||
      matchesGlob(rule.scheduledChange.channel, channel)
    : false; 
```
To : 
```const scChannelMatches = rule.scheduledChange
    ? (rule.scheduledChange.channel === null ||
        rule.scheduledChange.channel === '' ||
        rule.scheduledChange.channel === channel) &&
      matchesGlob(rule.scheduledChange.channel, channel)
    : false;```

### CODE REVIEW

**Comment by bhearsum** [comment]
I'm off for the next week. @gabrielBusta - can you look at this when you get a chance?

**Comment by AMUZY** [comment]
> I'm off for the next week. @gabrielBusta - can you look at this when you get a chance?

oh alright. I hope all is well though. Goodluck

**Comment by bhearsum** [comment]
@AMUZY - can you clarify what you think this is fixing? I couldn't find any cases that https://github.com/mozilla-releng/balrog/pull/3041 missed, but it's possible I overlooked something.

**Comment by AMUZY** [comment]
Hii @bhearsum you're back! Yeah I opened this PR around the same time #3041 was opened so that's why it still exists. Plus, I made my fix with less code changes I think?

**Comment by bhearsum** [comment]
This looks like a pretty reasonable fix for #2312 as well - nice work! Since the issue is already fixed I'm going to go ahead and close this though...

**Comment by AMUZY** [comment]
@bhearsum thank you for your review! means alot

**Pull request closed without merging**
