### PR TITLE
Bug 1472590 - Add Sentry support to the agent

### PR DESCRIPTION
**Pull request by nthomas-mozilla**

### CODE REVIEW

**Comment by mozbhearsum** [comment]
Do you think it's much work to get this finished up, @nthomas-mozilla? If you've got other priorities I might be able to drive it to completion.

**Comment by nthomas-mozilla** [comment]
I think this was a quick copy-and-paste patch which didn't get any testing. I guess we'd need to ask CloudOps to setup the environment, a SENTRY_DSN env IIRC. Also it looks like [raven](https://github.com/getsentry/raven-python) is being deprecated by [sentry-sdk](https://github.com/getsentry/sentry-python).

**Comment by mozbhearsum** [comment]
@rail has been poking at `sentry-sdk` for the other apps, and volunteered to finish this up.

**Comment by mozbhearsum** [comment]
Closing in favour of #1151

**Pull request closed without merging**
