### PR TITLE
Don't crash when logging an update query without osVersion or buildID

### LINKED ISSUE #2872: KeyError: KeyError('osVersion') in json get_update
Sentry Issue: [BALROG-PROD-PUBLIC-3B](https://mozilla.sentry.io/issues/4127930141/?referrer=github_integration)

```
KeyError: 'osVersion'
  File "auslib/web/public/helpers.py", line 17, in wrapper
    return f(*args, transaction=transaction, **kwargs)
  File "auslib/web/public/json.py", line 14, in get_update
    release, _, eval_metadata = AUS.evaluateRules(parameters, transaction=transaction)
  File "auslib/AUS.py", line 87, in evaluateRules
    rules = dbo.rules.getRulesMatchingQuery(updateQuery, fallbackChannel=getFallbackChannel(updateQuery["channel"]), transaction=transaction)
  File "auslib/db.py", line 1894, in getRulesMatchingQuery
    self.log.debug("%s doesn't match %s", rule["osVersion"], updateQuery["osVersion"])

KeyError: KeyError('osVersion')
(7 additional frame(s) were not displayed)
...
  File "auslib/db.py", line 202, in __exit__
    raise e
  File "auslib/web/public/helpers.py", line 17, in wrapper
    return f(*args, transaction=transaction, **kwargs)
  File "auslib/web/public/json.py", line 14, in get_update
    release, _, eval_metadata = AUS.evaluateRules(parameters, transaction=transaction)
  File "auslib/AUS.py", line 87, in evaluateRules
    rules = dbo.rules.getRulesMatchingQuery(updateQuery, fallbackChannel=getFallbackChannel(updateQuery["channel"]), transaction=transaction)
  File "auslib/db.py", line 1894, in getRulesMatchingQuery
    self.log.debug("%s doesn't match %s", rule["osVersion"], updateQuery["osVersion"])
```

### PR DESCRIPTION
**Pull request by jcristau**
Fixes #2872

### CODE REVIEW

**Review by gbrownmozilla — APPROVED** [review]
I was just about to write the same patch!

**Comment by jcristau** [comment]
I'll note that this bug was useful to me yesterday to verify the sentry integration for balrog-stage-public was working.  That's probably not a good enough reason not to fix it though :)

**Review by gabrielBusta — APPROVED** [review]

**Comment by jcristau** [comment]
One thought: this doesn't have a testcase, which seems wrong, so I'll try and fix that before merging.

**Comment by jcristau** [comment]
Added a test now.

**Pull request merged**
