### PR TITLE
partial match filter on releases

### PR DESCRIPTION
**Pull request by nazarenegena**
Fixes issue #1146 

Allows partial filtering of releases when a search value such as "fire 60"  is entered.

### CODE REVIEW

**Comment by gabrielBusta** [comment]
Thank you @nazarenegena

These changes are failing the linter check.

You can easily fix that by running this commands in your local repo:
```
cd ui/
yarn lint --fix
```

**Review by gabrielBusta — APPROVED** [review]
Thank you! The patch seems good and achieves the functionality described in #1146. In production the patch might slow down the filtering. In the development database there are about one hundred releases vs. the six thousand (and counting) releases in production. Slightly slower filtering seems like a good trade-off for the enhanced user experience (partial matching could be really useful.) I'd say we can land it, try it out and see. Dunno is trying it out in staging would be helpful (there's about six hundred releases in there)

**Review by gabrielBusta — APPROVED** [review]

**Comment by gabrielBusta** [comment]
It would be helpful for users if the matching parts of their search is highlighted in the results. This would give visual feedback about what part of their query matched.

**Comment by nazarenegena** [comment]
Thank you for the feedback.
should I go ahead and implement the highlighting and the performance check?

**Comment by gabrielBusta** [comment]
Regarding the highlighting, we have two options: we can open an issue for further follow-up and merge this pull request as it is, or you can address it directly here. The choice is yours. As for performance, what specific checks were you considering? It would be beneficial to gauge the code's performance on several thousand releases before deploying to production. However, if testing proves too cumbersome, we might consider deploying it to production directly and observing its performance there. If the speed is insufficient, we can always revert. We shouldn't prematurely optimize the code without identifying an issue. Should we encounter problems, there are various solutions to explore. For instance, we could think about debouncing the search. This approach would delay the search function execution until the user pauses typing for a brief moment, like 300ms, rather than executing on every keypress.

**Comment by nazarenegena** [comment]
Yes, you can go ahead and merge this request create a new issue for the highlights and assign it to me.

**Comment by gabrielBusta** [comment]
OK I created #3007 as a follow-up to this issue.

**Pull request merged**
